### ISSUE TITLE
error in MAS.py file

### ISSUE THREAD

**Issue by rohitdhote111** [LittleCoinCoin/Plant_Counting#6]
I am trying to run "Single_image_simulation.py" to visualize results but its showing error as below.

`PS D:\stand_count\Plant_Counting> & C:/Users/Rohit/AppData/Local/Microsoft/WindowsApps/python3.10.exe d:/stand_count/Plant_Counting/MAS/Single_Image_Simulation.py

Data Collection... Done
OTSU input: OTSU_R_rgb_68.jpg
Plant Fourier Transform Predictions input: PredictedRows_Img_0_94.json
Labelled Plants Adjusted Positions input: Adjusted_plant_positions_rgb_68.json
Simulation Definition:
Initializing Simulation class... The directory D:/stand_count/Plant_Counting/Tutorial/Output_General/Set3/Output_Meta_Simulation/Session_1/Simu_Steps_Pictures/20_2/Img_0 exists
No Folders had to be created
Done

Starting Search simulation:
X_Diffs [176 184  90  94 186 100  90 184 184]
kmeans.labels_ [0 0 1 1 0 1 1 0 0]
test_stat 31.155074571173557 p_value 9.064916975189307e-09
mean_nb_RALs [182.8  93.5]
Traceback (most recent call last):
  File "d:\stand_count\Plant_Counting\MAS\Single_Image_Simulation.py", line 118, in <module>
    MAS_Simulation.Perform_Search_Simulation(Search_Simulation_steps,
  File "d:\stand_count\Plant_Counting\MAS\MAS.py", line 1103, in Perform_Search_Simulation
    self.AD.Analyse_RowAs_Kmeans()
  File "d:\stand_count\Plant_Counting\MAS\MAS.py", line 836, in Analyse_RowAs_Kmeans
    index_small_grp = list(np.array((_indeces_grp0,_indeces_grp1))[np.where(means_grp == min(means_grp))][0][0])
**ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 2 dimensions. The detected shape was (2, 1) + inhomogeneous part.**
PS D:\stand_count\Plant_Counting>`

**Comment by LittleCoinCoin** [comment]
Hello,

My apologies for the delay!

Could you give me more context about your setup? For example, did you get this error while trying to run the tutorial or on your images?
If you are using your own images, could you share it with me (maybe via email if you don't want to openly share it)? I am asking because it might be an edge case we never encountered before.


Any other information such as your python version or numpy version might be helpful as well.

**Comment by rohitdhote111** [comment]
Thanks for the reply, your work is really impressive.

I have also written a simple script for the visualization of multi_images_simulation. let me know if it is of any use. I can create a separate branch OR add it here as well.

I solved the errors, I think the new environment could be the reason behind the errors.
I have tried to explain the errors and corrections below.

I found the solutions for the errors that I faced.

while running single_image_simulation.py, I faced 2 errors in MAS.py file which are explained below:
1. ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 2 dimensions. The detected shape was (2, 1) + inhomogeneous part.

on line number 836 of MAS.py file 
index_small_grp = list(np.array((_indeces_grp0,_indeces_grp1))[np.where(means_grp == min(means_grp))][0][0])

which I resolved by pre-converting tuples to arrays as follows
 ```
           # Find the group with the minimum mean
            min_mean_group_index = np.argmin(means_grp)

            _indeces_grp0 = np.array(_indeces_grp0)
            _indeces_grp1 = np.array(_indeces_grp1)

            # Get the indices associated with the group with the minimum mean
            index_small_grp = list((_indeces_grp0, _indeces_grp1))[min_mean_group_index]

            _indeces_grp0 = tuple(_indeces_grp0)
            _indeces_grp1 = tuple(_indeces_grp1)
```


2. TypeError: only integer scalar arrays can be converted to a scalar index
on line 877 from MAS.py file "self.RowAs = self.RowAs[:to_delete[i]-i] + self.RowAs[to_delete[i]-i+1:]"

which I resolved by flattening the "to_delete" array before using it as follows
```
            print("Rows to_delete", to_delete)
            nb_to_delete = len(to_delete)
            to_delete = [item for sublist in to_delete for item in sublist]
            for i in range(nb_to_delete):
                self.RowAs = self.RowAs[:to_delete[i]-i] + self.RowAs[to_delete[i]-i+1:]
```

**Comment by LittleCoinCoin** [comment]
Hello,

I'm glad you could find a fix to your problems!
Considering your solutions, it's still unclear why these errors happened only now but it's probably irrelevant since we have a fix :)

> I have also written a simple script for the visualization of multi_images_simulation. let me know if it is of any use. I can create a separate branch OR add it here as well.

That's great! Could you make a pull request that includes it?

Actually, could you also make a separate pull request with the 2 fixes that you included in this issue? That way your contribution will be recorded and we can keep things organized (even if this repo is not super big 😉 ).


> your work is really impressive

I don't know about that but thank you for the compliment anyway 😄

**Comment by rohitdhote111** [comment]
Hi, 
I have created a [pull request](https://github.com/LittleCoinCoin/Plant_Counting/pull/7) as per above suggestions. Please review and merge.
I will create a separate pull request for visualization file soon.
Thanks

**Comment by LittleCoinCoin** [comment]
Hello,
Just a heads up to confirm that I saw the pull request but I'm away for the next two weeks so it will be complicated to review it before then. But I'll get to it!

Thanks a lot for contributing!

**Comment by LittleCoinCoin** [comment]
Hey!

I just reviewed the your pulled request #7 suggesting changes and requesting you run `Single_Simulation_Image.py` to check the result, but I just remembered this was the origin of your problems.
Can you tell me if you had problems while running this script with the default values targeting the images in the tutorial or this was with your own images?
